### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Tricertops** [Tricertops/YAML#1]
#### Stage 1
  - [x] **Nodes** – model of YAML objects: Scalar, Sequence, Mapping.
  - [x] **Parser** – read YAML documents into Nodes, including their styles.
    - [x] **Lookup** – ability to find location of Node in original YAML document.
  - [x] **Emitter** – write Nodes into YAML documents, fully customized.
    - [ ] **Aliases** – correct behavior of references in Emitter.
  - [ ] **Tests** – unit tests of the above.

#### Stage 2
  - [ ] **Types** – interpret Scalar Nodes as higher-level types:
    - [ ] Null – support concept of null scalar.
    - [ ] Boolean – support all boolean values.
    - [ ] Int – support all integer features.
    - [ ] Float – support all floating-point number values.
    - [ ] Binary – support Base64 encoded sequences.
    - [ ] Timestamp – support ISO date values.
  - [ ] **Customized** – ability to provide interpretation to custom model obejcts.
  - [ ] **Tests** – unit tests of the above.

#### Stage 3
  - [ ] **Serialization** – YAML equivalent of `NSJSONSerialization`.
  - [ ] **Archivation** – YAML implementation `NSCoder`.
  - [ ] **Tests** – unit tests of the above.
